name: Semgrep Autofix

on:
  workflow_dispatch: {}

jobs:
  semgrep:
    name: Semgrep Autofix
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep with autofix
        run: semgrep --config .semgrep/print-to-logger.yml --autofix
